name: Build KeyX

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 安装额外工具
        run: |
          apt-get update
          apt-get install -y zip python-is-python3

      - name: 编译
        run: make

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: KeyX-build
          path: |
            out/KeyX-CN.zip
            out/KeyX-EN.zip
          if-no-files-found: error
